[package]
name = "fhir-sdk"
version = "0.16.0"
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = ["r5", "builders", "client", "docs", "dep-defaults"]
client = [
	"builders",
	"dep:async-trait",
	"dep:futures",
	"dep:reqwest",
	"dep:serde_json",
	"dep:tokio",
	"dep:tokio-retry",
	"dep:tracing",
	"dep:uuid",
]
builders = ["fhir-model/builders"]
r4b = ["fhir-model/r4b"]
r5 = ["fhir-model/r5"]
docs = []
full = ["r4b", "r5", "builders", "client", "docs", "dep-defaults"]

dep-defaults = ["reqwest?/default"]

http2 = ["reqwest?/http2"]
http3 = ["reqwest?/http3"]
default-tls = ["reqwest?/default-tls"]
native-tls = ["reqwest?/native-tls"]
native-tls-no-alpn = ["reqwest?/native-tls-no-alpn"]
native-tls-vendored = ["reqwest?/native-tls-vendored"]
native-tls-vendored-no-alpn = ["reqwest?/native-tls-vendored-no-alpn"]
rustls = ["reqwest?/rustls"]
rustls-no-provider = ["reqwest?/rustls-no-provider"]
blocking = ["reqwest?/blocking"]
charset = ["reqwest?/charset"]
cookies = ["reqwest?/cookies"]
gzip = ["reqwest?/gzip"]
brotli = ["reqwest?/brotli"]
zstd = ["reqwest?/zstd"]
deflate = ["reqwest?/deflate"]
multipart = ["reqwest?/multipart"]
stream = ["reqwest?/stream"]
socks = ["reqwest?/socks"]
hickory-dns = ["reqwest?/hickory-dns"]
system-proxy = ["reqwest?/system-proxy"]

[dependencies]
async-trait = { version = "0.1.89", optional = true }
fhir-model = { path = "../fhir-model", version = "0.13.0", default-features = false }
futures = { version = "0.3.32", optional = true }
reqwest = { version = "0.13.3", default-features = false, features = [
	"json",
	"query",
	"form",
], optional = true }
serde.workspace = true
serde_json = { workspace = true, optional = true }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["sync"], optional = true }
tokio-retry = { version = "0.3.1", optional = true }
tracing = { version = "0.1.44", optional = true }
uuid = { version = "1.23.1", features = ["v4"], optional = true }

[dev-dependencies]
neuer-error.workspace = true
tokio = { version = "1.52.3", features = ["full"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
wiremock = "0.6.5"

[package.metadata.docs.rs]
features = ["r5", "builders", "client", "docs", "dep-defaults"]
no-default-features = true
