[package]
name = "generate"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
fhir-model = { version = "0.13.0", default-features = false, features = [
  "r4b",
  "r5",
] }
heck = "0.5.0"
neuer-error.workspace = true
prettyplease = "0.2.37"
proc-macro2 = "1.0.106"
quote = "1.0.45"
regex = "1.12.3"
serde_json.workspace = true
syn = { version = "2.0.117", features = ["full"] }
